---

collections:
# Install collections ansible-collection-icinga-director and ansible-collection-icinga-business-process from Ansible Galaxy
- name: t_systems_mms.icinga_director
  version: 1.18.0
  source: https://galaxy.ansible.com

- name: t_systems_mms.icinga_business_process
  version: 1.0.2
  source: https://galaxy.ansible.com
