---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: "geerlingguy/docker-centos7-ansible:latest"
    volumes:
      - /sys:/sys:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    command: ""
  - name: rockylinux8
    image: "geerlingguy/docker-rockylinux8-ansible:latest"
    volumes:
      - /sys:/sys:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    command: ""
  - name: debian11
    image: "geerlingguy/docker-debian11-ansible:latest"
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    command: ""
provisioner:
  name: ansible
