---

- name: test if "icinga_plugins_path" is set correctly
  ansible.builtin.assert:
    that:
      - icinga_plugins_path is defined
    fail_msg: >
      icinga_plugins_path is not defined
      (this variable should point to the folder where your plugins are)

- name: install required dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ dependency_packages }}"
  tags:
    - install_dependencies

- name: copy icinga plugins to target node
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ icinga2_check_plugins_dest_plugins_dir }}/"
  with_fileglob:
    - "{{ icinga_plugins_path }}/*"
  when:
    - icinga_plugins_path is defined
    - icinga_plugins_path | length > 0

- name: "search for all files in plugins directory"
  ansible.builtin.find:
    paths: "{{ icinga2_check_plugins_dest_plugins_dir }}"
    recurse: yes
    file_type: any
  register: files_in_plugins_dir
  check_mode: no

- name: set plugins ownership
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "icinga"
    group: "icinga"
    mode: 0755
  loop: "{{ files_in_plugins_dir.files }}"
  loop_control:
    label: "{{ item.path }}"
  tags:
    - set_ownership
