---
- name: "Delete all icinga downtimes (host and service)"
  uri:
    url: "{{ icinga_api_uri }}:{{ icinga_api_port }}/v1/actions/remove-downtime?type=Downtime"
    user: "{{ icinga_api_user }}"
    password: "{{ icinga_api_password }}"
    validate_certs: False
    method: POST
    status_code: 200
    return_content: yes
    headers:
      Accept: 'application/json'
    body_format: json
    body: '{
             "filter": "host.name==\"{{ item }}\"",
             "pretty": true
           }'
  delegate_to: localhost
  with_inventory_hostnames:
    - "{{ groups[icinga_host_filter] }}"
