---
icinga_agent_package: icinga2
icinga_agent_registration: false
icinga_agent_enable_features:
  - "api.conf"
  - "notification.conf"
icinga_agent_ca_host_icinga_port: 5665
icinga_agent_constants_conf: |
  const PluginDir = "/usr/lib64/nagios/plugins"
  const PluginContribDir = "/usr/lib64/nagios/plugins"
  const ManubulonPluginDir = "/usr/lib64/nagios/plugins"
  const ZoneName = "{{ ansible_hostname }}"
  const NodeName = "{{ ansible_hostname }}"
  const TicketSalt = ""
icinga_agent_api_conf: |
  accept_config = true
  accept_commands = true
